Repository project-travel-mate/Travel-Mate, pull requests merged in 2018-06, with the labels that each got.

#72 fix issue #64
  Android/app/src/main/java/io/github/project_travel_mate/login/LoginActivity.java
Labels: need-changes

#102 Fixed # 82
  Android/app/src/main/res/layout/content_check_list.xml
  Android/app/src/main/res/layout/content_citylist.xml
  Android/build.gradle
Labels: under-review

#124 feat: Add Java 8 support & Convert to lambda expressions
  Android/app/build.gradle
  Android/app/src/main/java/adapters/CardViewOptionsAdapter.java
  Android/app/src/main/java/flipviewpager/adapter/BaseFlipAdapter.java
  Android/app/src/main/java/flipviewpager/view/FlipViewPager.java
  Android/app/src/main/java/io/github/project_travel_mate/LocationService.java
  Android/app/src/main/java/io/github/project_travel_mate/MainActivity.java
  Android/app/src/main/java/io/github/project_travel_mate/Splash.java
  Android/app/src/main/java/io/github/project_travel_mate/destinations/CityAdapter.java
  Android/app/src/main/java/io/github/project_travel_mate/destinations/CityFragment.java
  Android/app/src/main/java/io/github/project_travel_mate/destinations/description/FinalCityInfo.java
  Android/app/src/main/java/io/github/project_travel_mate/destinations/description/FinalCityInfoPresenter.java
  Android/app/src/main/java/io/github/project_travel_mate/destinations/description/FinalCityInfoView.java
  Android/app/src/main/java/io/github/project_travel_mate/destinations/description/PlacesOnMap.java
  Android/app/src/main/java/io/github/project_travel_mate/destinations/description/Tweets.java
  Android/app/src/main/java/io/github/project_travel_mate/destinations/description/TweetsAdapter.java
  Android/app/src/main/java/io/github/project_travel_mate/destinations/funfacts/FunFacts.java
  Android/app/src/main/java/io/github/project_travel_mate/login/LoginActivity.java
  Android/app/src/main/java/io/github/project_travel_mate/login/LoginPresenter.java
  Android/app/src/main/java/io/github/project_travel_mate/travel/Hotels.java
  Android/app/src/main/java/io/github/project_travel_mate/travel/MapRealTimeActivity.java
  Android/app/src/main/java/io/github/project_travel_mate/travel/ShoppingAdapter.java
  Android/app/src/main/java/io/github/project_travel_mate/travel/ShoppingCurrentCity.java
  Android/app/src/main/java/io/github/project_travel_mate/travel/TravelFragment.java
  Android/app/src/main/java/io/github/project_travel_mate/travel/mytrips/AddNewTrip.java
  Android/app/src/main/java/io/github/project_travel_mate/travel/mytrips/MyTripInfo.java
  Android/app/src/main/java/io/github/project_travel_mate/travel/mytrips/MyTripInfoImagesAdapter.java
  Android/app/src/main/java/io/github/project_travel_mate/travel/mytrips/MyTrips.java
  Android/app/src/main/java/io/github/project_travel_mate/travel/mytrips/MyTripsAdapter.java
  Android/app/src/main/java/io/github/project_travel_mate/travel/transport/CarDirections.java
  Android/app/src/main/java/io/github/project_travel_mate/travel/transport/SelectModeOfTransport.java
  Android/app/src/main/java/io/github/project_travel_mate/travel/transport/TrainAdapter.java
  Android/app/src/main/java/io/github/project_travel_mate/travel/transport/TrainList.java
  Android/app/src/main/java/io/github/project_travel_mate/utilities/ChecklistFragment.java
  Android/app/src/main/java/io/github/project_travel_mate/utilities/EmergencyFragment.java
  Android/app/src/main/java/io/github/project_travel_mate/utilities/ShareContact.java
  Android/app/src/main/java/io/github/project_travel_mate/utilities/UtilitiesFragment.java
  Android/app/src/main/java/objects/ChecklistItem.java
  Android/app/src/main/java/objects/City.java
  Android/app/src/main/java/objects/FunFact.java
  Android/app/src/main/java/objects/MapItem.java
  Android/app/src/main/java/objects/Trip.java
  Android/app/src/main/java/objects/Tweet.java
  Android/app/src/main/java/utils/Constants.java
  Android/app/src/main/java/utils/GPSTracker.java
  Android/app/src/main/java/utils/Services.java
  Android/app/src/main/java/utils/TouchImageView.java
  Android/app/src/main/java/utils/Utils.java
Labels: GSSoC, intermediate

#151 Fixes #71
  Android/app/src/main/java/io/github/project_travel_mate/login/LoginActivity.java
  Android/app/src/main/java/io/github/project_travel_mate/login/LoginPresenter.java
  Android/app/src/main/res/layout/activity_login.xml
  Android/app/src/main/res/values/strings.xml
Labels: in progress

#152 Fixes #142
  Android/app/src/main/res/layout/items_card_view.xml
Labels: in progress

#153 feat: Use API to fill profile info
  Android/app/src/main/java/io/github/project_travel_mate/ProfileActivity.java
  Android/app/src/main/java/objects/User.java
  Android/app/src/main/java/utils/DateUtils.java
  Android/app/src/main/res/layout/activity_profile.xml
  Android/app/src/main/res/values/strings.xml
Labels: in progress
